### ISSUE TITLE
mbsc-date demo not working - Property 'myBirthday' does not exist on type 'AboutPage'

### ISSUE THREAD

**Issue by peterennis** [acidb/mobiscroll-cli#1]
mbsc-date demo not working.
Following instructions froh here: https://download.mobiscroll.com/trial
Using an Ionic 4.0.0-beta.15 tabs app updated to Angular 7.
Repo: https://github.com/peterennis/aetabs
Site: https://aetabs.adaept.com/tabs/(about:about)

Running local shows this result:
![capture434](https://user-images.githubusercontent.com/140737/47967547-369c1800-e013-11e8-898c-ce4c8d3d57a4.png)

Prod build shows:
![capture435](https://user-images.githubusercontent.com/140737/47967553-4a477e80-e013-11e8-87d8-18e195084abd.png)

**Comment by dioslaska** [comment]
Hi there, sorry about the trouble.

The Ionic production build uses the AOT compiler by default, which has some stricter rules, than the JIT compiler, which is used for dev builds.
Like the error message states, the `myBirthday` property needs to be listed for your component, even if it does not have an initial value. E.g.:

```
@Component({
    selector: 'app-home',
    templateUrl: 'home.page.html',
    styleUrls: ['home.page.scss'],
})
export class HomePage {
  myBirthday: Date;
}
```

Let me know if this solves the issue.

**Comment by peterennis** [comment]
This commit:
https://github.com/peterennis/aetabs/commit/025c7fa5bf975dbadc485684d7ea6034cc3f720f
![capture436](https://user-images.githubusercontent.com/140737/47985400-558bc000-e08e-11e8-9db4-7198746343e8.png)
![capture437](https://user-images.githubusercontent.com/140737/47985409-59b7dd80-e08e-11e8-86fd-1ea94b6fe505.png)

It is not clear that Birthday needs to be clicked.
Where do I find styling options?

**Comment by dioslaska** [comment]
Hi Peter, since this is not a CLI issue, could you please move your question to the [Mobiscroll Forum](https://forum.mobiscroll.com/)?

Thanks a lot!
